### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by shajz** [benbernard/CommentTracker#10]
Hello!

We've been using this extension for a while but my team noticed yesterday morning that the Resolved/Unresolved button stopped showing up in code comments. They still appear in PR comments though.

Maybe GitHub made some changes to the DOM?

Could you take a look? We'd love to use this feature again :)

Good luck and thanks again for your work!

**Comment by benbernard** [comment]
Hey, sorry about this, yeah it looks like github changed something.  I use this everyday and it was working for most of yesterday for me, so maybe they were rolling it out slowly or something, but I see the problem right now.  Let me dig in and hopefully I can get a fix in quickly

**Comment by benbernard** [comment]
Okay, 1.1.9 is published in the store, I think you should be able to update your extensions now and get it.  Let me know if you have any comments (I will close for now)

**Comment by shajz** [comment]
Thanks for the quick fix ! It's all good now 🎉

**Comment by shajz** [comment]
Hi @benbernard, seems the plugin stopped working once more 😭 

Could you take a look ? Thanks :)

**Comment by benbernard** [comment]
Thanks for the heads up, probably related to my company shutting down ,
will investigate when I can

**Comment by benbernard** [comment]
Oops! Should've re-opened this issue.  Anyway, finally got off my butt and fixed this, fix is in `1.1.11` which is published and should be rolling out shortly.  Sorry for the long delay

**Comment by shajz** [comment]
Yesss, it works great \o/
Thanks for your work, don't worry about delays :)
